# Generated by Django 2.2 on 2019-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190613_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=400)),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
        migrations.AddField(
            model_name='avatar',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
