# Generated by Django 2.2 on 2019-06-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190613_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(),
        ),
    ]
