# Generated by Django 2.2 on 2019-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.TextField(),
        ),
    ]
